export const SHOW_MODAL = "SHOW_MODAL";
export const SUBMIT_CHANGES = "SUBMIT_CHANGES";
export const SHOW_DELETE_MESSAGE = "SHOW_DELETE_MESSAGE";
export const DELETE_BOOK = "DELETE_BOOK";
export const FETCH_BOOKS = "FETCH_BOOKS";
